- hosts: all
  vars_files:
    - "{{ ansible_facts['distribution'] }}.yml"

  tasks:
  - name: Installing Httpd Software
    package:
      name: "{{ package_name }}"
      state: present

  - name: Copying webpage
    template:
      dest: "{{ directory }}/index.html"
      src: web.html.j2

  - name: Start the service
    service:
      name: "{{ service_name }}"
      state: started
